//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.jiang.shanwe.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class StatisticsFragment_
    extends com.jiang.shanwe.fragment.StatisticsFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static StatisticsFragment_.FragmentBuilder_ builder() {
        return new StatisticsFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        rbWeek = ((RadioButton) hasViews.findViewById(com.jiang.shanwe.loveaccount.R.id.rbWeek));
        rbMonth = ((RadioButton) hasViews.findViewById(com.jiang.shanwe.loveaccount.R.id.rbMonth));
        lytPieChart = ((LinearLayout) hasViews.findViewById(com.jiang.shanwe.loveaccount.R.id.lytPieChart));
        ivSyncStafisticsChart = ((ImageView) hasViews.findViewById(com.jiang.shanwe.loveaccount.R.id.ivSyncStafisticsChart));
        lytBarChart = ((LinearLayout) hasViews.findViewById(com.jiang.shanwe.loveaccount.R.id.lytBarChart));
        rgStatistics = ((RadioGroup) hasViews.findViewById(com.jiang.shanwe.loveaccount.R.id.rgStatistics));
        if (rbMonth!= null) {
            rbMonth.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    StatisticsFragment_.this.renderMonthChart();
                }

            }
            );
        }
        if (ivSyncStafisticsChart!= null) {
            ivSyncStafisticsChart.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    StatisticsFragment_.this.syncStatisticsChart();
                }

            }
            );
        }
        if (rbWeek!= null) {
            rbWeek.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    StatisticsFragment_.this.renderWeekChart();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(com.jiang.shanwe.loveaccount.R.id.btnStatisticsPrevious);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        StatisticsFragment_.this.previousRangeChart();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.jiang.shanwe.loveaccount.R.id.btnStatisticsNext);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        StatisticsFragment_.this.nextRangeChart();
                    }

                }
                );
            }
        }
        renderWeekBarChart();
        renderWeekPieChart();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<StatisticsFragment_.FragmentBuilder_, com.jiang.shanwe.fragment.StatisticsFragment>
    {


        @Override
        public com.jiang.shanwe.fragment.StatisticsFragment build() {
            StatisticsFragment_ fragment_ = new StatisticsFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
